#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cmarkgfm
Version  : 0.4.2
Release  : 3
URL      : https://files.pythonhosted.org/packages/e2/a3/4021fbc17c5afe7f307d14eba0d6899a8e66b351ab65649b1c89c50a836d/cmarkgfm-0.4.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/e2/a3/4021fbc17c5afe7f307d14eba0d6899a8e66b351ab65649b1c89c50a836d/cmarkgfm-0.4.2.tar.gz
Summary  : Minimal bindings to GitHub's fork of cmark
Group    : Development/Tools
License  : MIT
Requires: cmarkgfm-license = %{version}-%{release}
Requires: cmarkgfm-python = %{version}-%{release}
Requires: cmarkgfm-python3 = %{version}-%{release}
Requires: cffi
BuildRequires : buildreq-distutils3
BuildRequires : cffi

%description
cmarkgfm - Bindings to GitHub's cmark
=====================================

Minimalist bindings to GitHub's fork of cmark.

Installation
------------

This package is published as `cmarkgfm <https://pypi.org/project/cmarkgfm/>`__
and can be installed with `pip` or `pipenv`::

    pip install --user cmarkgfm
    pipenv install cmarkgfm

Wheels are provided for macOS, Linux, and Windows for Python 2.7, 3.4, 3.5, and 3.6.

Usage
-----

High-level usage is really straightforward. To render normal CommonMark
markdown:

.. code-block:: python

    import cmarkgfm

    html = cmarkgfm.markdown_to_html(markdown_text)


To render GitHub-flavored markdown:

.. code-block:: python

    import cmarkgfm

    html = cmarkgfm.github_flavored_markdown_to_html(markdown_text)


Contributing
------------

Pull requests are welcome. :)


License
-------

This project is under the MIT License. It includes components under differing
copyright under the ``third_party`` directory in this source tree.

%package license
Summary: license components for the cmarkgfm package.
Group: Default

%description license
license components for the cmarkgfm package.


%package python
Summary: python components for the cmarkgfm package.
Group: Default
Requires: cmarkgfm-python3 = %{version}-%{release}

%description python
python components for the cmarkgfm package.


%package python3
Summary: python3 components for the cmarkgfm package.
Group: Default
Requires: python3-core
Provides: pypi(cmarkgfm)

%description python3
python3 components for the cmarkgfm package.


%prep
%setup -q -n cmarkgfm-0.4.2
cd %{_builddir}/cmarkgfm-0.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583332353
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cmarkgfm
cp %{_builddir}/cmarkgfm-0.4.2/LICENSE.txt %{buildroot}/usr/share/package-licenses/cmarkgfm/592ea524450874d50778dd5db4a8dd176a0261e2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cmarkgfm/592ea524450874d50778dd5db4a8dd176a0261e2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
